<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="62065" started-at="2020-06-24T08:14:25Z" finished-at="2020-06-24T08:15:27Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="62065" started-at="2020-06-24T08:14:25Z" finished-at="2020-06-24T08:15:27Z">
      <class name="Assessment.AddUser">
        <test-method status="PASS" signature="inititialize()[pri:0, instance:Assessment.AddUser@776a6d9b]" name="inititialize" is-config="true" duration-ms="53263" started-at="2020-06-24T10:14:25Z" finished-at="2020-06-24T10:15:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inititialize -->
        <test-method status="FAIL" signature="addUser(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Assessment.AddUser@776a6d9b]" name="addUser" duration-ms="5734" started-at="2020-06-24T10:15:19Z" data-provider="getData" finished-at="2020-06-24T10:15:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[FName1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[LName1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Pass1]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Company AAA]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Admin@mail.com]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[082555]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User1] but found [[[ChromeDriver: chrome on WINDOWS (b37cf58822c2e0334a9a43fdc92c9b34)] -> xpath: /html/body/table]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User1] but found [[[ChromeDriver: chrome on WINDOWS (b37cf58822c2e0334a9a43fdc92c9b34)] -> xpath: /html/body/table]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at Assessment.AddUser.addUser(AddUser.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addUser -->
        <test-method status="FAIL" signature="addUser(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:Assessment.AddUser@776a6d9b]" name="addUser" duration-ms="2055" started-at="2020-06-24T10:15:24Z" data-provider="getData" finished-at="2020-06-24T10:15:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[FName2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[LName2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[User2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Pass2]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Company BBB]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Customer]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[cusomter@mail.com]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[083444]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [User2] but found [[[ChromeDriver: chrome on WINDOWS (b37cf58822c2e0334a9a43fdc92c9b34)] -> xpath: /html/body/table]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [User2] but found [[[ChromeDriver: chrome on WINDOWS (b37cf58822c2e0334a9a43fdc92c9b34)] -> xpath: /html/body/table]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:179)
	at Assessment.AddUser.addUser(AddUser.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addUser -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:Assessment.AddUser@776a6d9b]" name="teardown" is-config="true" duration-ms="761" started-at="2020-06-24T10:15:26Z" finished-at="2020-06-24T10:15:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Assessment.AddUser -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
